# Generated by Django 2.2.6 on 2019-10-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timePlan', '0003_auto_20191018_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='actividades',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timePlan.Categoria'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timePlan.Categoria'),
        ),
    ]
