# Generated by Django 2.2.6 on 2019-12-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timePlan', '0004_perfilusuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='_perfilusuario_amigos_+', to='timePlan.PerfilUsuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='solicitudes',
            field=models.ManyToManyField(blank=True, related_name='_perfilusuario_solicitudes_+', to='timePlan.PerfilUsuario'),
        ),
    ]
